apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vgre-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vgre-operator-role
subjects:
- kind: ServiceAccount
  name: vgre-operator-controller-manager
  namespace: vgre-system
