// Unified Hugging Face tokenizer.json engine (BpeTokenizer::loadHf):
//
//  1. Always-on: a synthetic-but-real tokenizer.json (unicode escapes, both
//     merge encodings, added special tokens, cl100k-family split pattern) plus
//     honest rejection of unsupported (SentencePiece-style) files.
//  2. Gated (skip 77 if the files are absent): token-for-token parity against
//     reference ids produced by the real Hugging Face `tokenizers` library
//     (tests/data/hf_tokenizer_ref_*.json, regenerated by
//     tools/gen_hf_tokenizer_reference.py) for
//       • GPT-2   (ByteLevel built-in split; two-file form cross-checked too)
//       • Qwen2.5 (cl100k-family Split regex, 151k vocab, chat specials)
//     over a corpus of contractions, CJK/Greek/Cyrillic, Arabic-Indic digits,
//     emoji, punctuation runs, CRLF/multi-newline and special-token text.
//
// argv: [1] = tests/data dir, [2] = gpt2 tokenizer.json, [3] = qwen2
// tokenizer.json, [4] = gpt2 vocab.json, [5] = gpt2 merges.txt.

#include "vgre/xla/tokenizer.h"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include "vgre/common/json.h"

using vgre::xla::BpeTokenizer;
namespace fs = std::filesystem;

static int g_fail = 0;
#define CHECK(cond, msg)                                                   \
    do {                                                                   \
        if (!(cond)) {                                                     \
            std::printf("FAIL: %s  (%s:%d)\n", (msg), __FILE__, __LINE__); \
            ++g_fail;                                                      \
        }                                                                  \
    } while (0)

// Run every case in one reference file against `tok`; returns cases checked.
static int runReference(BpeTokenizer& tok, const std::string& refPath) {
    std::ifstream f(refPath, std::ios::binary);
    if (!f) { std::printf("FAIL: missing reference %s\n", refPath.c_str()); ++g_fail; return 0; }
    std::stringstream ss;
    ss << f.rdbuf();
    vgre::common::json::Value root;
    if (!vgre::common::json::parse(ss.str(), root)) { ++g_fail; return 0; }
    const auto* cases = root.find("cases");
    int n = 0;
    for (const auto& c : cases->arr) {
        const std::string text = c.find("text")->asString();
        std::vector<int> want;
        for (const auto& v : c.find("ids")->arr) want.push_back((int)v.asNumber());
        std::vector<int> got = tok.encodeHf(text);
        if (got != want) {
            std::printf("FAIL: id mismatch on case %d (%zu got vs %zu want): %.40s...\n",
                        n, got.size(), want.size(), text.c_str());
            size_t lim = std::min(got.size(), want.size());
            for (size_t i = 0; i < lim; ++i)
                if (got[i] != want[i]) {
                    std::printf("  first diff at %zu: got %d want %d\n", i, got[i], want[i]);
                    break;
                }
            ++g_fail;
        }
        // Decode must reproduce the input exactly (byte-level: lossless).
        if (tok.decodeHf(want) != text) { std::printf("FAIL: decode roundtrip case %d\n", n); ++g_fail; }
        ++n;
    }
    return n;
}

int main(int argc, char** argv) {
    const std::string dataDir = argc > 1 ? argv[1] : "tests/data";
    const std::string gpt2Json = argc > 2 ? argv[2] : "";
    const std::string qwenJson = argc > 3 ? argv[3] : "";
    const std::string gpt2Vocab = argc > 4 ? argv[4] : "";
    const std::string gpt2Merges = argc > 5 ? argv[5] : "";

    // ── 1a. Synthetic tokenizer.json: full format surface, no external files ──
    {
        fs::path tj = fs::temp_directory_path() / "vgre_tok_hf.json";
        {
            std::ofstream f(tj);
            // "Ġa" = Ġa (byte-level space+a). Merges use both encodings:
            // legacy "Ġ a" string and ["ab","c"] pair. Special: <|eot|> id 900.
            f << R"({"version":"1.0",
                "added_tokens":[{"id":900,"content":"<|eot|>","special":true}],
                "normalizer":{"type":"NFC"},
                "pre_tokenizer":{"type":"Sequence","pretokenizers":[
                  {"type":"Split","pattern":{"Regex":"(?i:'s|'t|'re|'ve|'m|'ll|'d)|[^\\r\\n\\p{L}\\p{N}]?\\p{L}+|\\p{N}{1,3}| ?[^\\s\\p{L}\\p{N}]+[\\r\\n]*|\\s*[\\r\\n]+|\\s+(?!\\S)|\\s+"},"behavior":"Isolated","invert":false},
                  {"type":"ByteLevel","add_prefix_space":false,"trim_offsets":false,"use_regex":false}]},
                "post_processor":null,
                "decoder":{"type":"ByteLevel"},
                "model":{"type":"BPE","dropout":null,"unk_token":null,
                  "vocab":{"a":10,"b":11,"c":12,"1":13,"2":14,"3":15,"4":16,
                           "Ġ":17,"ab":20,"abc":30,"Ġa":40,
                           "12":21,"123":31,"1234":50},
                  "merges":["a b",["ab","c"],"Ġ a","1 2",["12","3"],["123","4"]]}})";
        }
        BpeTokenizer t;
        CHECK(t.loadHf(tj.string()), "loadHf parses full tokenizer.json");
        CHECK(t.hfReady(), "hf mode active");
        CHECK(t.hfVocabSize() == 901, "vocab size = max id + 1 (special included)");
        CHECK(t.specialTokenId("<|eot|>") == 900, "special token id lookup");
        CHECK(t.specialTokenId("<|nope|>") == -1, "absent special -> -1");
        // Merges from both encodings apply: "abc" -> 30, " a" -> Ġa = 40.
        CHECK(t.encodeHf("abc") == std::vector<int>{30}, "string+pair merges apply");
        CHECK(t.encodeHf(" a") == std::vector<int>{40}, "legacy-string merge applies");
        // cl100k digit rule: "1234" splits "123"|"4" -> [31,16]. If the split
        // were wrong (one piece), the ["123","4"] merge would fire -> [50].
        {
            auto ids = t.encodeHf("1234");
            CHECK(ids == (std::vector<int>{31, 16}), "digit {1,3} grouping");
            CHECK(t.decodeHf(ids) == "1234", "digit roundtrip");
        }
        // Special splits the text and maps to its reserved id.
        {
            auto ids = t.encodeHf("ab<|eot|>c");
            CHECK(ids == (std::vector<int>{20, 900, 12}), "special token splits + id");
            CHECK(t.decodeHf(ids) == "ab<|eot|>c", "special roundtrip");
        }
        fs::remove(tj);
    }

    // ── 1b. Unsupported files are rejected, not approximated ────────────────
    {
        fs::path bad = fs::temp_directory_path() / "vgre_tok_bad.json";
        {   // SentencePiece-style (Metaspace normalizer, no ByteLevel)
            std::ofstream f(bad);
            f << R"({"normalizer":{"type":"Sequence","normalizers":[{"type":"Prepend","prepend":"▁"}]},
                     "pre_tokenizer":null,
                     "model":{"type":"BPE","vocab":{"a":1},"merges":[]}})";
        }
        BpeTokenizer t;
        CHECK(!t.loadHf(bad.string()), "SentencePiece-style file rejected");
        CHECK(!t.loadHf("/nonexistent/tokenizer.json"), "missing file rejected");
        fs::remove(bad);
    }

    // ── 2. Real-model parity vs the HF `tokenizers` reference ───────────────
    bool ranReal = false;
    if (!gpt2Json.empty() && fs::exists(gpt2Json)) {
        BpeTokenizer t;
        CHECK(t.loadHf(gpt2Json), "loadHf(real GPT-2 tokenizer.json)");
        CHECK(t.hfVocabSize() == 50257, "GPT-2 vocab 50257");
        int n = runReference(t, dataDir + "/hf_tokenizer_ref_gpt2.json");
        std::printf("gpt2 tokenizer.json: %d reference cases checked\n", n);
        CHECK(n >= 15, "all gpt2 cases present");

        // Cross-check: the two-file GPT-2 form must agree with tokenizer.json
        // on non-special text (same vocab, same merges, same split).
        if (!gpt2Vocab.empty() && fs::exists(gpt2Vocab) && fs::exists(gpt2Merges)) {
            BpeTokenizer t2;
            CHECK(t2.loadGpt2(gpt2Vocab, gpt2Merges), "loadGpt2(real files)");
            const char* samples[] = {
                "I'm sure it's John's — isn't it? He'LL win.",
                "The year 2026 has 365 days; pi is 3.14159.",
                "café Ελληνικά 中文 🚀\n\nnew  paragraph\r\n",
            };
            for (const char* s : samples)
                CHECK(t2.encodeGpt2(s) == t.encodeHf(s), "two-file == tokenizer.json ids");
        }
        ranReal = true;
    }
    if (!qwenJson.empty() && fs::exists(qwenJson)) {
        BpeTokenizer t;
        CHECK(t.loadHf(qwenJson), "loadHf(real Qwen2.5 tokenizer.json)");
        CHECK(t.specialTokenId("<|im_start|>") == 151644, "qwen <|im_start|> id");
        int n = runReference(t, dataDir + "/hf_tokenizer_ref_qwen2.json");
        std::printf("qwen2 tokenizer.json: %d reference cases checked\n", n);
        CHECK(n >= 15, "all qwen2 cases present");
        ranReal = true;
    }
    if (!ranReal && g_fail == 0) {
        std::printf("SKIP: no real tokenizer.json fixtures (set VGRE_HF_FIXTURES or "
                    "download to ~/.vgre_cache/hf_gpt2, hf_qwen2); synthetic checks passed\n");
        return 77;
    }

    if (g_fail == 0) { std::printf("test_tokenizer_hf: ALL CHECKS PASSED\n"); return 0; }
    std::printf("test_tokenizer_hf: %d FAILURE(S)\n", g_fail);
    return 1;
}
