#pragma once

#include "cudnn_internal.h"

#include <cstdint>
#include <unordered_map>
#include <vector>

enum cudnnBackendDescriptorType_t {
    CUDNN_BACKEND_OPERATION_DESCRIPTOR = 0,
    CUDNN_BACKEND_OPERATION_CONVOLUTION_FORWARD_DESCRIPTOR = 1,
    CUDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_DATA_DESCRIPTOR = 2,
    CUDNN_BACKEND_OPERATION_CONVOLUTION_BACKWARD_FILTER_DESCRIPTOR = 3,
    CUDNN_BACKEND_OPERATION_POOLING_FORWARD_DESCRIPTOR = 4,
    CUDNN_BACKEND_OPERATION_POOLING_BACKWARD_DESCRIPTOR = 5,
    CUDNN_BACKEND_OPERATION_ACTIVATION_FORWARD_DESCRIPTOR = 6,
    CUDNN_BACKEND_OPERATION_ACTIVATION_BACKWARD_DESCRIPTOR = 7,
    CUDNN_BACKEND_OPERATION_MATMUL_DESCRIPTOR = 8,
    CUDNN_BACKEND_OPERATION_REDUCTION_DESCRIPTOR = 9,
    CUDNN_BACKEND_OPERATION_SOFTMAX_DESCRIPTOR = 10,
    CUDNN_BACKEND_OPERATION_BN_FINALIZE_STATISTICS_DESCRIPTOR = 11,
    CUDNN_BACKEND_OPERATION_NORM_FORWARD_DESCRIPTOR = 12,
    CUDNN_BACKEND_OPERATION_NORM_BACKWARD_DESCRIPTOR = 13,
    CUDNN_BACKEND_OPERATION_RESAMPLE_DESCRIPTOR = 14,
    CUDNN_BACKEND_OPERATION_CONCAT_DESCRIPTOR = 15,
    CUDNN_BACKEND_OPERATION_SIGNAL_DESCRIPTOR = 16,
    CUDNN_BACKEND_OPERATION_GEN_STATS_DESCRIPTOR = 17,
    CUDNN_BACKEND_OPERATION_BN_BWD_WEIGHTS_DESCRIPTOR = 18,
    CUDNN_BACKEND_OPERATION_RNG_DESCRIPTOR = 19,
    CUDNN_BACKEND_TENSOR_DESCRIPTOR = 20,
    CUDNN_BACKEND_CONVOLUTION_DESCRIPTOR = 21,
    CUDNN_BACKEND_POINTWISE_DESCRIPTOR = 22,
    CUDNN_BACKEND_GENSTATS_DESCRIPTOR = 23,
    CUDNN_BACKEND_ENGINECFG_DESCRIPTOR = 24,
    CUDNN_BACKEND_ENGINE_DESCRIPTOR = 25,
    CUDNN_BACKEND_MATMUL_DESCRIPTOR = 26,
    CUDNN_BACKEND_OPERATIONSET_DESCRIPTOR = 27,
    CUDNN_BACKEND_HANDLE_DESCRIPTOR = 28,
    CUDNN_BACKEND_HEURIN_DESCRIPTOR = 29,
    CUDNN_BACKEND_ENGINHEUR_DESCRIPTOR = 30,
    CUDNN_BACKEND_KNOB_CHOICE_DESCRIPTOR = 31,
    CUDNN_BACKEND_KNOB_DESCRIPTOR = 32,
    CUDNN_BACKEND_VARIANT_PACK_DESCRIPTOR = 33,
    CUDNN_BACKEND_LAYOUT_INFO_DESCRIPTOR = 34,
    CUDNN_BACKEND_OPERATION_RNN_DESCRIPTOR = 35,
    CUDNN_BACKEND_OPERATION_ATTENTION_DESCRIPTOR = 36,
    CUDNN_BACKEND_OPERATION_POINTWISE_DESCRIPTOR = 37,
    CUDNN_BACKEND_OPERATION_RESAMPLE_FWD_DESCRIPTOR = 38,
    CUDNN_BACKEND_OPERATION_RESAMPLE_BWD_DESCRIPTOR = 39
};

enum cudnnBackendAttributeName_t {
    CUDNN_ATTR_POINTWISE_MODE = 0,
    CUDNN_ATTR_POINTWISE_MATH_PREC = 1,
    CUDNN_ATTR_POINTWISE_NAN_PROPAGATION = 2,
    CUDNN_ATTR_CONVOLUTION_SPATIAL_DIMS = 10,
    CUDNN_ATTR_CONVOLUTION_DILATIONS = 11,
    CUDNN_ATTR_CONVOLUTION_FILTER_STRIDES = 12,
    CUDNN_ATTR_CONVOLUTION_PRE_PADDINGS = 13,
    CUDNN_ATTR_CONVOLUTION_POST_PADDINGS = 14,
    CUDNN_ATTR_CONVOLUTION_STRIDES = 15,
    CUDNN_ATTR_CONVOLUTION_GROUP_COUNT = 16,
    CUDNN_ATTR_CONVOLUTION_BWD_DATA_ALGO = 17,
    CUDNN_ATTR_CONVOLUTION_BWD_FILTER_ALGO = 18,
    CUDNN_ATTR_CONVOLUTION_FWD_ALGO = 19,
    CUDNN_ATTR_TENSOR_DIMENSIONS = 30,
    CUDNN_ATTR_TENSOR_STRIDES = 31,
    CUDNN_ATTR_TENSOR_DATA_TYPE = 32,
    CUDNN_ATTR_TENSOR_VECTORIZED_DIM = 33,
    CUDNN_ATTR_TENSOR_VECTOR_COUNT = 34,
    CUDNN_ATTR_TENSOR_IS_VIRTUAL = 35,
    CUDNN_ATTR_TENSOR_IS_BY_VALUE = 36,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_X = 40,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_W = 41,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_Y = 42,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_CONV_DESC = 43,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DY = 44,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_W = 45,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_DX = 46,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_CONV_DESC = 47,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DY = 48,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_X = 49,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_DW = 50,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_CONV_DESC = 51,
    CUDNN_ATTR_OPERATION_MATMUL_ADESC = 60,
    CUDNN_ATTR_OPERATION_MATMUL_BDESC = 61,
    CUDNN_ATTR_OPERATION_MATMUL_CDESC = 62,
    CUDNN_ATTR_OPERATION_MATMUL_DDESC = 63,
    CUDNN_ATTR_OPERATION_MATMUL_MDESC = 64,
    CUDNN_ATTR_OPERATIONPOOLING_XDESC = 70,
    CUDNN_ATTR_OPERATIONPOOLING_YDESC = 71,
    CUDNN_ATTR_OPERATIONPOOLING_IDXDESC = 72,
    CUDNN_ATTR_OPERATIONPOOLING_PDESC = 73,
    CUDNN_ATTR_OPERATIONPOOLING_BWD_DXDESC = 74,
    CUDNN_ATTR_OPERATIONPOOLING_BWD_DYDESC = 75,
    CUDNN_ATTR_OPERATIONPOOLING_BWD_IDXDESC = 76,
    CUDNN_ATTR_OPERATIONPOOLING_BWD_PDESC = 77,
    CUDNN_ATTR_OPERATION_ACTIVATION_XDESC = 80,
    CUDNN_ATTR_OPERATION_ACTIVATION_YDESC = 81,
    CUDNN_ATTR_OPERATION_ACTIVATION_DESC = 82,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_DXDESC = 83,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_DYDESC = 84,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_YDESC = 85,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_DESC = 86,
    CUDNN_ATTR_VARIANT_PACK_UNIQUE_IDS = 100,
    CUDNN_ATTR_VARIANT_PACK_DATA_POINTERS = 101,
    CUDNN_ATTR_VARIANT_PACK_INTERMEDIATES = 102,
    CUDNN_ATTR_VARIANT_PACK_WORKSPACE = 103,
    CUDNN_ATTR_ENGINEHEUR_MODE = 110,
    CUDNN_ATTR_ENGINECFG_ENGINE = 120,
    CUDNN_ATTR_ENGINECFG_KNOB_CHOICES = 121,
    CUDNN_ATTR_ENGINECFG_INTERMEDIATE_INFO = 122,
    CUDNN_ATTR_EXECUTION_PLAN_HANDLE = 130,
    CUDNN_ATTR_EXECUTION_PLAN_ENGINE_CONFIG = 131,
    CUDNN_ATTR_EXECUTION_PLAN_WORKSPACE_SIZE = 132,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_ALPHA = 160,
    CUDNN_ATTR_OPERATION_CONVOLUTION_FORWARD_BETA = 161,
    CUDNN_ATTR_OPERATION_ACTIVATION_FORWARD_ALPHA = 162,
    CUDNN_ATTR_OPERATION_ACTIVATION_FORWARD_BETA = 163,
    CUDNN_ATTR_OPERATION_POOLING_FORWARD_ALPHA = 164,
    CUDNN_ATTR_OPERATION_POOLING_FORWARD_BETA = 165,
    CUDNN_ATTR_OPERATION_SOFTMAX_ALPHA = 166,
    CUDNN_ATTR_OPERATION_SOFTMAX_BETA = 167,
    CUDNN_ATTR_OPERATION_REDUCTION_ALPHA = 168,
    CUDNN_ATTR_OPERATION_REDUCTION_BETA = 169,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_ALPHA = 170,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_DATA_BETA = 171,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_ALPHA = 172,
    CUDNN_ATTR_OPERATION_CONVOLUTION_BWD_FILTER_BETA = 173,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_ALPHA = 174,
    CUDNN_ATTR_OPERATION_ACTIVATION_BWD_BETA = 175,
    CUDNN_ATTR_OPERATION_POOLING_BWD_ALPHA = 176,
    CUDNN_ATTR_OPERATION_POOLING_BWD_BETA = 177,
    CUDNN_ATTR_OPERATION_REDUCTION_DESC = 178,
    CUDNN_ATTR_OPERATION_MATMUL_ALPHA = 179,
    CUDNN_ATTR_OPERATION_MATMUL_BETA = 180,
    CUDNN_ATTR_OPERATION_ATTENTION_QDESC = 200,
    CUDNN_ATTR_OPERATION_ATTENTION_KDESC = 201,
    CUDNN_ATTR_OPERATION_ATTENTION_VDESC = 202,
    CUDNN_ATTR_OPERATION_ATTENTION_ODESC = 203,
    CUDNN_ATTR_OPERATION_ATTENTION_NUMHEADS = 204,
    CUDNN_ATTR_OPERATION_ATTENTION_SCALE = 205,
    CUDNN_ATTR_OPERATION_ATTENTION_CAUSAL_MASK = 206,  // bool: 1=apply causal mask
    CUDNN_ATTR_ENGINE_OPERATION_GRAPH = 500,
    CUDNN_ATTR_OPERATIONSET_OPS = 501,
    // Pointwise operation attributes
    CUDNN_ATTR_OPERATION_POINTWISE_XDESC          = 600,
    CUDNN_ATTR_OPERATION_POINTWISE_BDESC          = 601,  // optional bias
    CUDNN_ATTR_OPERATION_POINTWISE_YDESC          = 602,
    CUDNN_ATTR_OPERATION_POINTWISE_PW_DESCRIPTOR  = 603,
    CUDNN_ATTR_OPERATION_POINTWISE_ALPHA1         = 604,
    CUDNN_ATTR_OPERATION_POINTWISE_ALPHA2         = 605,
    // Engine heuristic result
    CUDNN_ATTR_ENGINEHEUR_RESULTS                 = 610,
    CUDNN_ATTR_ENGINEHEUR_OPERATION_GRAPH         = 611,
    // Resample attributes
    CUDNN_ATTR_OPERATION_RESAMPLE_XDESC           = 620,
    CUDNN_ATTR_OPERATION_RESAMPLE_YDESC           = 621,
    CUDNN_ATTR_OPERATION_RESAMPLE_ALPHA           = 622,
    CUDNN_ATTR_OPERATION_RESAMPLE_BETA            = 623,
    CUDNN_ATTR_OPERATION_RESAMPLE_NANPROP         = 624,
    CUDNN_ATTR_OPERATION_RESAMPLE_MODE            = 625,
    CUDNN_ATTR_OPERATION_RESAMPLE_SPATIAL_DIMS    = 626,
    CUDNN_ATTR_OPERATION_RESAMPLE_STRIDES         = 627,
    CUDNN_ATTR_OPERATION_RESAMPLE_WINDOW_DIMS     = 628,
    CUDNN_ATTR_OPERATION_RESAMPLE_PRE_PADDING     = 629,
    CUDNN_ATTR_OPERATION_RESAMPLE_POST_PADDING    = 630,
    // NORM_FORWARD / NORM_BACKWARD dedicated attributes (real BatchNorm/LayerNorm)
    // phase=0 → INFERENCE: mean/invVar are inputs (running stats, invVar stores running_var)
    // phase=1 → TRAINING : mean/invVar are outputs (saved for backward pass)
    CUDNN_ATTR_OPERATION_NORM_FWD_XDESC          = 700, // input tensor desc [N,C,H,W]
    CUDNN_ATTR_OPERATION_NORM_FWD_YDESC          = 701, // output tensor desc [N,C,H,W]
    CUDNN_ATTR_OPERATION_NORM_FWD_SCALE_DESC     = 702, // gamma per-channel [1,C,1,1]
    CUDNN_ATTR_OPERATION_NORM_FWD_BIAS_DESC      = 703, // beta  per-channel [1,C,1,1]
    CUDNN_ATTR_OPERATION_NORM_FWD_MEAN_DESC      = 704, // running mean (infer) / saved mean out (train) [1,C,1,1]
    CUDNN_ATTR_OPERATION_NORM_FWD_INV_VAR_DESC   = 705, // running variance (infer) / saved inv_std out (train)
    CUDNN_ATTR_OPERATION_NORM_FWD_EPSILON_DESC   = 706, // epsilon scalar (by-value float tensor)
    CUDNN_ATTR_OPERATION_NORM_FWD_MODE           = 707, // 0=BN_spatial, 1=LayerNorm, 2=InstanceNorm
    CUDNN_ATTR_OPERATION_NORM_FWD_PHASE          = 708, // 0=INFERENCE, 1=TRAINING
    // RNG operation attributes (CUDNN_BACKEND_OPERATION_RNG_DESCRIPTOR)
    CUDNN_ATTR_OPERATION_RNG_YDESC               = 720, // output tensor desc
    CUDNN_ATTR_OPERATION_RNG_SEED                = 721, // uint64 seed for Philox4x32
    CUDNN_ATTR_OPERATION_RNG_DIST                = 722, // 0=uniform[0,1), 1=normal(0,1), 2=Bernoulli
    CUDNN_ATTR_OPERATION_RNG_BERNOULLI_PROB      = 723  // keep probability for Bernoulli (float)
};

struct BackendNode {
    cudnnBackendDescriptorType_t type;
    std::unordered_map<int, std::vector<uint64_t>> attrs;
    bool finalized = false;
};

extern std::unordered_map<uintptr_t, BackendNode> g_backendNodes;
extern uintptr_t g_nextBackendId;

BackendNode* getNode(uintptr_t id);
const std::vector<uint64_t>* getAttrVec(const BackendNode* node, int attr);
uintptr_t getAttrUint64(const BackendNode* node, int attr, uintptr_t def = 0);
float getAttrFloat(const BackendNode* node, int attr, float def = 0.0f);

// Exposed for use in cudnn_graph.cpp (CONV_NORM fusion)
std::unordered_map<uintptr_t, void*> cudnn_parseVariantPack(void* variantPack);
cudnnStatus_t cudnn_executeFusedConvBN(cudnnHandle_t handle,
                                        uintptr_t convNodeId,
                                        uintptr_t bnNodeId,
                                        void* variantPack);
