//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (equivalent to controller-gen). DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VgreCluster) DeepCopyInto(out *VgreCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy returns a deep copy of the VgreCluster.
func (in *VgreCluster) DeepCopy() *VgreCluster {
	if in == nil {
		return nil
	}
	out := new(VgreCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VgreCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a pointer.
func (in *VgreClusterList) DeepCopyInto(out *VgreClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VgreCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of the VgreClusterList.
func (in *VgreClusterList) DeepCopy() *VgreClusterList {
	if in == nil {
		return nil
	}
	out := new(VgreClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *VgreClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of VgreClusterSpec into another.
func (in *VgreClusterSpec) DeepCopyInto(out *VgreClusterSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of the VgreClusterSpec.
func (in *VgreClusterSpec) DeepCopy() *VgreClusterSpec {
	if in == nil {
		return nil
	}
	out := new(VgreClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of VgreClusterStatus into another.
func (in *VgreClusterStatus) DeepCopyInto(out *VgreClusterStatus) {
	*out = *in
}

// DeepCopy returns a deep copy of the VgreClusterStatus.
func (in *VgreClusterStatus) DeepCopy() *VgreClusterStatus {
	if in == nil {
		return nil
	}
	out := new(VgreClusterStatus)
	in.DeepCopyInto(out)
	return out
}
