#!/usr/bin/env python3
"""Generate include/vgre/xla/unicode_tables.inc — compact codepoint-range tables
for the Unicode properties the HF-style BPE pre-tokenizers need:

    \\p{L}  (letters:  Lu Ll Lt Lm Lo)
    \\p{N}  (numbers:  Nd Nl No)

Derived from the Python `unicodedata` database (the same UCD the regex engines
behind Hugging Face `tokenizers` use), emitted as sorted inclusive [lo, hi]
uint32 ranges for binary search. Regenerate with:

    python3 tools/gen_unicode_tables.py > include/vgre/xla/unicode_tables.inc
"""
import sys
import unicodedata

L_CATS = {"Lu", "Ll", "Lt", "Lm", "Lo"}
N_CATS = {"Nd", "Nl", "No"}


def ranges(cats):
    out, lo = [], None
    for cp in range(0x110000):
        ch = chr(cp)
        member = unicodedata.category(ch) in cats
        if member and lo is None:
            lo = cp
        elif not member and lo is not None:
            out.append((lo, cp - 1))
            lo = None
    if lo is not None:
        out.append((lo, 0x10FFFF))
    return out


def emit(name, rs, f):
    f.write(f"static const CpRange {name}[] = {{\n")
    for i in range(0, len(rs), 4):
        row = ", ".join(f"{{0x{lo:X}, 0x{hi:X}}}" for lo, hi in rs[i:i + 4])
        f.write(f"    {row},\n")
    f.write("};\n")
    f.write(f"static const size_t {name}Count = sizeof({name}) / sizeof({name}[0]);\n\n")


def main():
    f = sys.stdout
    f.write("// Generated by tools/gen_unicode_tables.py — do not edit by hand.\n")
    f.write(f"// Unicode database version: {unicodedata.unidata_version}\n\n")
    emit("kUnicodeLetterRanges", ranges(L_CATS), f)
    emit("kUnicodeNumberRanges", ranges(N_CATS), f)


if __name__ == "__main__":
    main()
